spring:
  profiles: dev
  datasource:
    driver-class-name:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/static/

server:
  port: 8080

---

spring:
  profiles: operation
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    url: jdbc:mysql://strong1133.cizleuoo6ppg.ap-northeast-2.rds.amazonaws.com/strong1133DB
    username: strong1133
    password: tjrwls455
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080



