
spring:
  profiles: prod
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    url: jdbc:mysql://strong1133.cizleuoo6ppg.ap-northeast-2.rds.amazonaws.com/strong1133DB
    username: strong1133
    password: tjrwls455
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8081



