spring:
  profiles: dev
  datasource:
    driver-class-name:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/

server:
  port: 8080



